version: '2'

services:
  tweet-collector:
    command: "bash -c 'yarn && yarn start'"
    image: node
    volumes:
      - ./:/project
    links:
      - postgres
    ports:
      - 8000:8000
    environment:
      - DATABASE_HOST=postgres

  postgres:
    image: postgres:9.6
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=root
      - POSTGRES_DB=tweets
    ports:
      - 5432:5432